services:

  pixelcant:
    container_name: pixelcant_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  postgres:
    image: postgres
    container_name: pixelcant_psql
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5m
